enable-module-update = true
parallel-jobs = 1

[YouTube-Revanced]
app-name = "YouTube"
included-patches = "'Custom branding icon MMT' 'Custom branding name for YouTube'"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
rv-brand = "Youtube Revanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = "-e 'Custom branding' -OcustomName='Meu YouTube'"

[YouTube-Morphe]
app-name = "YouTube"
included-patches = "'Custom branding icon MMT Blue'"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[YouTube-ANDDEA]
app-name = "YouTube"
included-patches = "'Custom branding icon MMT Green' 'Custom branding name for YouTube'"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ANDDEA"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
patcher-args = "-e 'Custom branding' -OcustomIcon='MMT Green' -OcustomName='Meu YouTube'"
